overrides:
  '@adobe/css-tools@<4.3.1': '>=4.3.1'
  '@adobe/css-tools@<4.3.2': '>=4.3.2'
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@babel/runtime@<7.26.10': '>=7.26.10'
  '@babel/traverse@<7.23.2': '>=7.23.2'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@>=7.0.0 <7.0.5: '>=7.0.5'
  dset@<3.1.4: '>=3.1.4'
  jose@>=3.0.0 <=4.15.4: '>=4.15.5'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  json5@<1.0.2: '>=1.0.2'
  json5@>=2.0.0 <2.2.2: '>=2.2.2'
  micromatch@<4.0.8: '>=4.0.8'
  semver@>=6.0.0 <6.3.1: '>=6.3.1'
  serialize-javascript@>=6.0.0 <6.0.2: '>=6.0.2'
  tmp@<=0.2.3: '>=0.2.4'
  webpack@>=5.0.0 <5.76.0: '>=5.76.0'
  webpack@>=5.0.0-alpha.0 <5.94.0: '>=5.94.0'
  word-wrap@<1.2.4: '>=1.2.4'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
