name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint code
        run: pnpm run lint

      - name: Run tests
        run: pnpm test

      - name: Build the project
        run: pnpm run build

      - name: Check if FIREBASE_TOKEN is available
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
          echo "FIREBASE_TOKEN is missing!"
          exit 1
          fi

      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: pnpm dlx firebase-tools deploy --token "$FIREBASE_TOKEN"
